### PR TITLE
Add PublicHoliday service and controller

### PR DESCRIPTION
**Pull request by shuningliu**
In this PR, we add an endpoint `api/publicholidays/get` that can be used to get information
about the holidays of a country at a particular year.

### CODE REVIEW

**Comment by shuningliu** [comment]
Closes #12 
Closes #11

**Comment by jcucsb** [comment]
Green on CI and code looks good for the PublicHolidayService and PublicHolidayTest.

**Comment by heyyysus** [comment]
Passes test and behaves as expected on swagger-ui. LGTM

**Comment by YYA0** [comment]
LGTM

**Review by heyyysus — APPROVED** [review]
Passes test and behaves as expected on swagger-ui. LGTM

**Review by sergioacolis — APPROVED** [review]
LGTM

**Pull request merged**
